# Generated by Django 4.2.7 on 2025-09-26 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_report', models.TextField(help_text='Original medical report text')),
                ('drug', models.CharField(help_text='Extracted drug name', max_length=255)),
                ('adverse_events', models.JSONField(default=list, help_text='List of adverse events')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], help_text='Severity level of the adverse events', max_length=20)),
                ('outcome', models.CharField(choices=[('recovered', 'Recovered'), ('ongoing', 'Ongoing'), ('fatal', 'Fatal')], help_text='Patient outcome', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the report was processed')),
            ],
            options={
                'verbose_name': 'Adverse Event Report',
                'verbose_name_plural': 'Adverse Event Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
